cuts: abs(probeScEta)>1.56 and tagPt>40 and probePt>20 and mass>80 and mass<100 and  probePassEleVeto==0 and abs(tagScEta)<2.5 and abs(probeScEta)<2.5

plots:
  pt:
    var: probePt
    bins: 100
    xmin: 0
    xmax: 100
    weightstr_mc: weight_clf
    type: dataMC
    ratio: True
    ratio_lim: (0.8,1.2),

  mass:
    var: mass
    bins: 120
    xmin: 60
    xmax: 120
    weightstr_mc: weight_clf
    type: dataMC
    ratio: True
    ratio_lim: (0.8,1.2),
    
  eta:
    var: probeScEta
    bins: 300
    xmin: -3
    xmax: 3
    weightstr_mc: weight_clf
    type: dataMC
    ratio: True
    ratio_lim: (0.8,1.2),

  phi:
    var: probePhi
    bins: 300
    xmin: -3.14
    xmax: 3.14
    weightstr_mc: weight_clf
    type: dataMC
    leg_loc: lower_right
    ratio: True
    ratio_lim: (0.8,1.2),
    
  rho:
    var: rho
    bins: 60
    xmin: 0
    xmax: 60
    weightstr_mc: weight_clf
    type: dataMC
    ratio: True
    ratio_lim: (0.8,1.2),

  Isolations:
    var: probePhoIso, probeChIso03worst
    bins: 100
    xmin: 0
    xmax: 10
    weightstr_mc: weight_clf
    exts: ['_corr','_corr_1Reg']
    type: dataMC
    ratio: True
    ratio_lim: (0.8,1.2),
    
  chIsolation:
    var: probeChIso03
    bins: 100
    xmin: 0
    xmax: 10
    weightstr_mc: weight_clf
    exts: ['_corr','_corr_1Reg']
    type: dataMC
    logy: True
    ratio: True
    ratio_lim: (0.8,1.2),

  ULphoID:
    var: newULPhoID
    bins: 80
    xmin: -0.8
    xmax: 1
    weightstr_mc: weight_clf
    exts: ['corrAll','corrAllFinal']
    ratio: True
    type: dataMC
    ratio_lim: (0.8,1.2),
